export const ACTIONS = {
  GET_PRODUCTS: "GET_PRODUCTS",
  GET_PRODUCT_DETAILS: "GET_PRODUCT_DETAILS",
  GET_CART: "GET_CART",
  CHANGE_CART_LENGTH: "CHANGE_CART_LENGTH",
};

export const JSON_API_PRODUCTS = "http://localhost:8003/plants";

export const PRODUCT_LIMIT = 12;
